package view;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Font;

/**
 *
 * @author yury-antergos
 */
public class SobreGUI extends javax.swing.JPanel {

    /**
     * Creates new form SobreGUI
     */
    public SobreGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLogoChat = new javax.swing.JLabel();

        setPreferredSize(new Dimension(223, 342));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setText("Versão:");
        add(jLabel2);
        jLabel2.setBounds(10, 130, 56, 17);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("1.3");
        add(jLabel3);
        jLabel3.setBounds(70, 130, 20, 15);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setText("Desenvolvedores:");
        add(jLabel4);
        jLabel4.setBounds(10, 170, 131, 17);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Diogo R. L. da Silveira - C173398");
        add(jLabel6);
        jLabel6.setBounds(10, 190, 213, 15);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Ricardo F. Souto - C13CH5");
        add(jLabel7);
        jLabel7.setBounds(10, 210, 213, 15);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Wanderson M. Oliveira - C202754");
        add(jLabel8);
        jLabel8.setBounds(10, 230, 213, 15);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Yury R. Anunciação - C203360");
        add(jLabel9);
        jLabel9.setBounds(10, 250, 213, 15);

        lblLogoChat.setIcon(new ImageIcon(SobreGUI.class.getResource("/img/chat_logo4.png"))); // NOI18N
        lblLogoChat.setAlignmentX(0.5F);
        lblLogoChat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblLogoChat);
        lblLogoChat.setBounds(35, 10, 155, 100);
        
        JLabel lblEmojisPor = new JLabel("Emojis:");
        lblEmojisPor.setFont(new Font("Dialog", Font.BOLD, 13));
        lblEmojisPor.setBounds(10, 285, 91, 15);
        add(lblEmojisPor);
        
        JLabel lblTwi = new JLabel("Twemoji");
        lblTwi.setFont(new Font("Dialog", Font.PLAIN, 12));
        lblTwi.setBounds(70, 285, 70, 15);
        add(lblTwi);
        
        JLabel lblBibliotecaPor = new JLabel("Biblioteca:");
        lblBibliotecaPor.setFont(new Font("Dialog", Font.BOLD, 13));
        lblBibliotecaPor.setBounds(10, 312, 108, 15);
        add(lblBibliotecaPor);
        
        JLabel lblHtmlcleaner = new JLabel("HtmlCleaner");
        lblHtmlcleaner.setFont(new Font("Dialog", Font.PLAIN, 12));
        lblHtmlcleaner.setBounds(92, 312, 91, 15);
        add(lblHtmlcleaner);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblLogoChat;
}
